import { StyleSheet } from 'react-native';
import { responsiveHeight, responsiveWidth, responsiveFontSize } from 'react-native-responsive-dimensions'; // Adjust these imports as needed
import colors from '../../../assets/colors/colors'; // Adjust the path according to your project structure

const styles = StyleSheet.create({
    safe:{
        height:'100%',
        justifyContent:'space-between',
        //backgroundColor:colors.calenderbackground,
    },
currentMonthYear:{
    //top:20,
    //top:responsiveHeight(2.45),
    //marginHorizontal:20,
    marginHorizontal:responsiveWidth(4.68),
},
datetitle:{
    fontFamily:'Inconsolata-Bold',
    color:colors.textwhite,
    //fontSize:20,
    fontSize:responsiveFontSize(2.5),
},
DatelistWrapper:{
    //height:93,
    height:responsiveHeight(11.3),
    //backgroundColor:colors.textblack,
},
DateWrapper:{
    //top:25,
    //top:responsiveHeight(2),
    //height:100,
    height:responsiveHeight(11.5),
    marginLeft:responsiveWidth(4.68),
    //backgroundColor:colors.textwhite,
},
Datelist:{
    flexDirection:'column',
    //backgroundColor:colors.TextBlood,
    //top:10,
    top:responsiveWidth(2.28),
    //marginRight:20,
    marginRight:responsiveWidth(4.68),
    //borderRadius:15,
    borderRadius:responsiveWidth(3.5),
    //width:55,
    width:responsiveWidth(12.75),
    //height:70,
    height:responsiveHeight(8.55),
    borderColor:colors.border,
    //borderWidth :1,
    borderWidth:responsiveWidth(0.25),
    alignItems: 'center',
    justifyContent: 'center',
},
DateText:{
    fontFamily:'Inconsolata-Bold',
    color:colors.textgray,
    //fontSize:20,
    fontSize:responsiveFontSize(2.2),
},
date:{
    fontFamily:'Inconsolata-ExtraBold',
    color:colors.textwhite,
    //fontSize:24,
    fontSize:responsiveFontSize(2.7),
},
day:{
    fontFamily:'Inconsolata-ExtraBold',
    color:colors.textwhite,
    //fontSize:14,
    fontSize:responsiveFontSize(1.6),
},
TimeWrapper:{
    //top:30,
    //top:responsiveHeight(2),
    //marginLeft:20,
    marginLeft:responsiveWidth(4.68),
    //backgroundColor:colors.textwhite,
},
timeText:{
    fontFamily:'Inconsolata-Bold',
    color:colors.textgray,
    //fontSize:20,
    fontSize:responsiveFontSize(2.2),
},
Timelist:{
    //backgroundColor:colors.TextBlood,
    //marginRight:20,
    marginRight:responsiveWidth(4.68),
    //top:10,
    top:responsiveWidth(2.28),
    //borderRadius:10,
    borderRadius:responsiveWidth(2.4),
    //width:80,
    width:responsiveWidth(18.58),
    //height:35,
    height:responsiveHeight(4.27),
    borderColor:colors.border,
    //borderWidth:1,
    borderWidth:responsiveWidth(0.25),
    alignItems:'center',
    justifyContent: 'center',
},
timelistWrapper:{
    height:50,
    //backgroundColor:colors.textblack,
},
time:{
    fontFamily:'Inconsolata-Medium',
    color:colors.textwhite,
    //fontSize:16,
    fontSize:responsiveFontSize(2),
},
bookingContainer:{
    //top:-10,
    flexDirection:'column',
    backgroundColor:colors.calenderbackground,
    width:'100%',
    height:'30%',
    //height:responsiveHeight(30),
    //borderRadius:20,
    //borderRadius:responsiveWidth(4.5),
    borderTopLeftRadius:responsiveWidth(4.5),
    borderTopRightRadius:responsiveWidth(4.5),
    justifyContent:'space-between',
    alignItems:'center',
},
bookbox:{
    backgroundColor:colors.textwhite,
    width:'100%',
    height:'75%',
    //borderRadius:20,
    //borderRadius:responsiveWidth(4.5),
    borderTopLeftRadius:responsiveWidth(4.5),
    borderTopRightRadius:responsiveWidth(4.5),
    justifyContent:'center',
    alignItems:"center",
},
bookbutton:{
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor:colors.textblack,
    width:'60%',
    height:'50%',
    //borderRadius:20,
    borderRadius:responsiveWidth(4.5),
},
book:{
    fontFamily: 'Inconsolata-Bold',
    color:colors.textwhite,
    //fontSize:24,
    fontSize:responsiveFontSize(2.7),
},
showDateNTime:{        
    //paddingHorizontal:40,
    paddingHorizontal:responsiveWidth(4.20),
    width:'100%',
    flexDirection:'row',
    alignItems: 'center',
    justifyContent:'space-between',
   // backgroundColor:colors.textblack,
},
calNdate:{
    flexDirection:'row',
    alignItems:'center',
},
datebooked:{
    //marginLeft:10,
    marginLeft:responsiveWidth(2),
    fontFamily:'Inconsolata-Bold',
    //fontSize:20,
    fontSize:responsiveFontSize(2.1),
},
timebooked:{
    fontFamily:'Inconsolata-Medium',
    //fontSize:16,
    fontSize:responsiveFontSize(1.8),
},
modal: {
    justifyContent: "flex-end",
    margin: 0,
    //backgroundColor:colors.textdarkgold,
  },
modalContent: {
    backgroundColor: "#161616",
    paddingHorizontal: responsiveWidth(4.68),
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    minHeight: responsiveHeight(40),
    paddingBottom: 20,
    justifyContent:'space-between',
},
center: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
},
barIcon: {
    width: 60,
    height: 5,
    backgroundColor: "#bbb",
    borderRadius: 3,
},
bookingdetails:{
    alignItems: "center",
    justifyContent: "center",
},
bookingdetailText:{
    fontFamily:'Inconsolata-Bold',
    fontSize:responsiveFontSize(2.6),
    color:colors.textwhite,
},
StoreDateTime:{
    flexDirection:'column',
    height: responsiveHeight(18),
    justifyContent:'space-around',     
    //backgroundColor:colors.textdarkgold,
},
storeHead:{
    flexDirection: 'row',
    justifyContent:'space-between',
    alignItems:'center',
    //backgroundColor:colors.cardbackground,
},
StoreDateTimeTitle:{
    fontFamily:'Inconsolata-Medium',
    fontSize:responsiveFontSize(2.4),
    color:colors.calenderbackground,
},
StoreDateTimeSelected:{
    fontFamily:'Inconsolata-Bold',
    fontSize:responsiveFontSize(2.4),
    color:colors.border,
},
ConfirmBookingButton:{
    backgroundColor:colors.textwhite,
    height:responsiveHeight(5.5),
    borderRadius:responsiveFontSize(1.5),
    alignItems:'center',
    justifyContent: 'center',
},
ConfirmBookingText:{
    fontFamily: 'Inconsolata-Bold',
    color:colors.textblack,
    fontSize:responsiveFontSize(2.2),
},
});

export default styles;
